# Setup

In [59]:
import mariadb
import pandas as pd
import dataframe_image as dfi

In [2]:
db_connection = mariadb.connect(
    user='root',
    password='root',
    host='localhost',
    port=3307,
    database='wca_dev',
)

# Statistiche "settimanali"

## Medagliere italiano & Numero di solve italiano

In [60]:
with open(r"SQL_queries\Country medal table in a specific year.sql", "r") as f:
    query_text = f.read()

query_medal_table_og = query_text.split(";\n")[1]

with open(r"SQL_queries\Number of solves by people in one county in a specific year.sql", "r") as f:
    query_text = f.read()

setting, query_solves_og = query_text.split(";\n")

In [61]:
print(setting)

/* This script cannot be executed directly, you need to replace the folloqing parameters
 * to make it work:
@YEAR@
@COUNTRY@
*/

In [62]:
YEAR = "2026"
COUNTRY = "'Italy'"

query_medal_table = query_medal_table_og.replace('@YEAR@', YEAR).replace('@COUNTRY@', COUNTRY)
query_solves = query_solves_og.replace('@YEAR@', YEAR).replace('@COUNTRY@', COUNTRY)

In [91]:
cur = db_connection.cursor()

cur.execute(query_medal_table)
medal_table = cur.fetchall()

cur.execute(query_solves)
solves = cur.fetchall()

cur.close()

In [121]:
cols = ('rankk', 'person_id', 'person_name', 'Ori', 'Argenti', 'Bronzi', 'Totali', 'Gare', 'Medaglie_per_gara', 'rank_ratio')

df_medal_table = pd.DataFrame(medal_table, columns=cols)
df_medal_table = df_medal_table.rename_axis(index="Index", axis=0)

#df_medal_table

In [97]:
cols = ('rankk', 'person_id', 'person_name', 'num_solves', 'num_DNF', 'total_attempts', '|', 'num_competitions', 'num_solves_per_comp', 'rank_solves_comp')

df_solves = pd.DataFrame(solves, columns=cols)
df_solves = df_solves.rename_axis(index="Index", axis=0)

#df_solves

In [122]:
df_medal_table.head(5)

,rankk,person_id,person_name,Ori,Argenti,Bronzi,Totali,Gare,Medaglie_per_gara,rank_ratio
Index,,,,,,,,,,
0,1,2021MARI04,Paolo Marino,14,14,9,37,12,3.0833,7
1,2,2016GAMM01,Vincenzo Maria Gammino,13,14,15,42,24,1.7500,21
2,3,2018LOCA01,Valerio Locatelli,13,9,5,27,9,3.0000,8
3,4,2023CREA02,Christian Crea,12,8,12,32,12,2.6667,12
4,5,2021SALE01,Sofia Saletnich,10,13,10,33,7,4.7143,3

In [99]:
df_solves.head(5)

,rankk,person_id,person_name,num_solves,num_DNF,total_attempts,|,num_competitions,num_solves_per_comp,rank_solves_comp
Index,,,,,,,,,,
0,1,2009PROV01,Matteo Provasi,2179,45,2224,|,40,54.4750,75
1,2,2020TOMA01,Fabian Tomasović,1168,97,1265,|,22,53.0909,82
2,3,2023CREA02,Christian Crea,940,22,962,|,12,78.3333,4
3,4,2024RICC01,Riccardo Fiumefreddo,915,4,919,|,17,53.8235,79
4,5,2021MARI04,Paolo Marino,911,73,984,|,12,75.9167,10

In [154]:
df_medal_table_st = df_medal_table.head(25).style.hide(axis=0)
await dfi.export_async(df_medal_table_st, r"Images\Rank 1.png", dpi=200)

In [155]:
df_medal_table_st = df_medal_table.sort_values("rank_ratio").head(25).style.hide(axis=0)
await dfi.export_async(df_medal_table_st, r"Images\Rank 2.png", dpi=200)

In [158]:
df_solves_st = df_solves.head(25).style.hide(axis=0)
await dfi.export_async(df_solves_st, r"Images\Solve 1.png", dpi=200)

In [159]:
df_solves_st = df_solves.sort_values("rank_solves_comp").head(25).style.hide(axis=0)
await dfi.export_async(df_solves_st, r"Images\Solve 2.png", dpi=200)

# Altro